name: Pull_request
on: pull_request
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        uses: npm install
      - name: Tets
        run: react-scripts test
      - name: Run app
        run: export PUBLIC_URL=/ || set PUBLIC_URL=/&& react-scripts start
      - name: Lint
        run: tsc --noEmit && eslint src/**/*.ts{,x}
      - name: Build
        run: react-scripts build
